{
 "title": "c338maayanp",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Completed",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{container=\"orderbookapi\",namespace=\"c338-maayanp-dev\"} |~ \"Completed\""
    }
   ]
  },
  { "title": "Classic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Jenkins Disk Space",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"c338-maayanp-dev\", container=\"orderbookapi\"} ) / sum(container_memory_usage_bytes{namespace=\"c338-maayanp-dev\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_cpu_usage_seconds_total{namespace=\"c338-maayanp-dev\",container=\"orderbookapi\"}) /sum(container_cpu_usage_seconds_total{namespace=\"c338-maayanp-dev\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}